# 基础镜像
FROM redis
# author
MAINTAINER ddmit

# 挂载目录
VOLUME /home/ddmit/redis
# 创建目录
RUN mkdir -p /home/ddmit/redis
# 指定路径
WORKDIR /home/ddmit/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/ddmit/redis/redis.conf
