# 基础镜像
FROM nginx
# author
MAINTAINER ddmit

# 挂载目录
VOLUME /home/ddmit/projects/ddmit-ui
# 创建目录
RUN mkdir -p /home/ddmit/projects/ddmit-ui
# 指定路径
WORKDIR /home/ddmit/projects/ddmit-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/ddmit/projects/ddmit-ui
